### ISSUE TITLE
Multiple validations fires at the same time.

### ISSUE THREAD

**Issue by VikasSathe3189** [ghiscoding/angular-validation#168] opened 2017-10-09 08:07 UTC
I'm having an issue with validation, that if I have added required field validation and with that, I am using min length validation and alphaNum validation. And if I hit submit button, all validation fires at the same time.
Is there any way to display error messages for a particular error. Like it will first display error for required and then if entered data less than given min length then it will display for error min length and finally for alphanumeric validation.

eg:

`<input type="text" 
name="username" 
class="form-control" 
ng-model="userModel.UserName"
placeholder="Enter Username"
validation="required:alt=Username is required|min_len:4:alt=Username must be at least 4 characters.|alpha_num:alt=:Username may only contain letters and numbers"/>`

and its showing something like that.

Username is required. Username must be at least 4 characters. Username may only contain letters and numbers.

**Comment by ghiscoding** [comment] 2017-10-09 15:02
Take a look at the [Wiki - Global Options](https://github.com/ghiscoding/angular-validation/wiki/Global-Options). The following option is what you need

```javascript
// display only last error message on each input element (False default)
// for example if 3 errors are on the element, only the last error would show up
displayOnlyLastErrorMsg: true,
```

**Comment by VikasSathe3189** [comment] 2017-10-09 15:36
Thank you for your reply,
but the issue is still there. Somehow it's not working for me.
As you suggested I have added "displayOnlyLastErrorMsg: true," in my code. And still, I am getting the same results i.e multiple errors are displaying.


`
function ApplicationCtrl($scope, $rootScope, $route, ValidationService)  
  var myValidation = new ValidationService();
    myValidation .setGlobalOptions({ debounce: 1500, scope: $scope, preValidateFormElements: true, displayOnlyLastErrorMsg: true });
};
`

**Comment by ghiscoding** [comment] 2017-10-11 16:50
It's a little hard to help you without a Plunker that reproduces your problem, but let's try couple of things. Could you try with the `$scope` instead of the service to see if that helps. Something like this
```javascript
$scope.$validationOptions = {
    debounce: 1500, 
    displayOnlyLastErrorMsg: false,
    preValidateFormElements: false 
}
```
Also, you didn't mention if that was the error displayed in the Validation Summary or the input itself. I don't think this option of `displayOnlyLastErrorMsg` has any effect on the Validation Summary. Lastly, I'm also not sure of the result when combining `displayOnlyLastErrorMsg: true` and `preValidateFormElements: true`, that might be the cause of the issue, if so please try to switch `preValidateFormElements` to false and click on your save/submit button to see if you get only 1 error message shown under your input.

Side note, my Unit Tests are broken since probably a year after Gulp & Chrome Debugger updated to newer versions. I spent some time trying to fix them but without any luck.

**Comment by VikasSathe3189** [comment] 2017-10-16 06:28
Thank you for your help.
The issue has been resolved, the changes I have been doing was not injecting properly through the code.
So I have made the changes in the .js file. 
And it worked for me. I am able to display last error messages.
Thank you again,  really appreciated your help.

**Comment by ghiscoding** [comment] 2017-10-16 13:26
You're welcome, I will close the issue then.

**Closed by ghiscoding** 2017-10-16 13:26 UTC
