### ISSUE TITLE
Control set to invalid when updateOn 'blur' used

### ISSUE THREAD

**Issue by jmichaud-ips** [ghiscoding/angular-validation#117] opened 2016-05-25 21:23 UTC
I have created a plunker to show my problem.  Steps to reproduce behavior in my plunker: http://plnkr.co/edit/larsq0

1. go to directive page
2. click in Name field
3. add a letter to the name
4. tab or click off
5. The input will highlight red even though the only validation is required.

If you click back on the control and off again, then the red goes away.  On inspection, I can see its still set to ng-invalid.  I have narrowed this behavior down to ngAnimate.  If I don't inject that into the module, then I don't get the behavior.  Using angular version 1.5.5.  I'm using ng-model-options="{ updateOn: 'blur' }" because my production owner wants the error text to stay until they leave the control.

**Comment by ghiscoding** [comment] 2016-05-26 04:11
There's probably a timing issue since ngModel is not in sync and I'm not sure when the validation kicks in. If you want to help, you can use the unminified version of Angular-Validation and troubleshooting. If not, it might take a while since I'm not personally using that option.

**Comment by ghiscoding** [comment] 2016-06-15 03:50
Hello, I tried to copy your code locally to troubleshoot but I can't seem to reproduce it locally. I mean, it works as intended. Did I miss something? Can you check the code, I created a new folder under [more-examples/ngModelOptionBlur](https://github.com/ghiscoding/angular-validation/tree/master/more-examples/ngModelOptionBlur)

**Comment by jmichaud-ips** [comment] 2016-06-20 13:47
I double checked the plunker code, it shows the problem I was having.  I looked at the code in ngModelOptionBlur, app.js is missing the injection of 'ngAnimate'.  I found that to trigger my problem.

**Comment by ghiscoding** [comment] 2016-06-20 16:54
oh ok so is this problem resolved then? If so, I would close this issue.

**Comment by jmichaud-ips** [comment] 2016-06-20 17:03
I wouldn’t say the problem is resolved, its still an issue.  I just no longer need the functionality.  You could mark it as not going to fix.

**Comment by ghiscoding** [comment] 2016-06-20 18:01
Ah ok sorry I misunderstood. I just realized that you meant I was missing ngAnimate in the copy I made.

**Closed** 2016-06-21 02:53 UTC
Labels: wontfix
